apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
spec:
  type: state.azure.cosmosdb
  version: v1
  metadata:
    - name: url
      value: https://cosmos-tasks-tracker-state-store-mop3f6.documents.azure.com:443/
    - name: masterKey
      value: "IICiyJImfZpuCfddL7KaLP9DzjSISD9SA5cSuaen9ZdFSnzGE9UOOaHw9l3JpIRqRWCxm5cpkMUEACDbykYlcw=="
    - name: database
      value: tasksmanagerdb
    - name: collection
      value: taskscollection
scopes:
  - tasksmanager-backend-api