apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: externaltasksmanager
spec:
  type: bindings.azure.storagequeues
  version: v1
  metadata:
    - name: storageAccount
      value: "sttaskstrackermop3f6"
    - name: storageAccessKey
      value: "EDZQi1UjJbPrGRXUpB3hFB8XBwgORXKuP7yzKJgRISYVENaxgfG0NxJGHdikUAykruKSY+nLj4+S+AStTsK88g=="
    - name: queue
      value: "external-tasks-queue"
    - name: decodeBase64
      value: "true"
    - name: route
      value: /externaltasksprocessor/process